<a href="https://colab.research.google.com/github/RiyaMaurya1/Deep_learning/blob/main/ANN_Feed_Forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
X = np.array([
    [1,0,1,0],
    [1,0,1,1],
    [0,1,0,1]
])

y = np.array([[1],[1],[0]])

X.shape

(3, 4)

In [7]:
inputneurons = X.shape[1]

# equal to no. of features
hiddenneurons = 4 

outputneurons = 1



In [8]:
weightshidden = np.random.uniform(size = (inputneurons, hiddenneurons))
biashidden = np.random.uniform(size = (1, hiddenneurons))
biasoutput = np.random.uniform(size = (1, outputneurons))
weightsoutput = np.random.uniform(size = (hiddenneurons, outputneurons))

In [9]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))


In [12]:
# feed forward 

# Step 1: Apply linear equation
fx1 = np.dot(X, weightshidden) + biashidden

fx1

array([[1.78051693, 1.7008361 , 1.19860004, 1.91764095],
       [2.48052887, 2.69347068, 1.82269492, 2.01202712],
       [1.67069485, 1.89892681, 1.26363678, 1.87382455]])

In [13]:
# Step 2: Apply activation for non-linearity
z = sigmoid(fx1)

z

array([[0.85576068, 0.8456439 , 0.76827565, 0.87187514],
       [0.9227655 , 0.93664026, 0.86088918, 0.88205408],
       [0.84166844, 0.86977001, 0.77965152, 0.86690019]])

In [18]:
# Step - 3 : apply linear equation on output of hidden layer
fx2 = np.dot(z, weightsoutput) + biasoutput

# Step - 4 : apply activation on output layer
output = sigmoid(fx2)

In [15]:
output

array([[0.92594182],
       [0.93672593],
       [0.92704156]])

In [16]:
y

array([[1],
       [1],
       [0]])

In [ ]:
# As there is huge difference between output and target, we will perform backpropagation to rewrite the weights and get closer results. 